baseURL = 'https://www.rainsay.net/'
languageCode = 'zh-CN'
title = 'Rainsay Note Blog'

theme = 'LoveIt'

[menus]
  [[menus.main]]
    identifier = 'posts'
    name = 'Posts'
    pageRef = '/posts/'
    weight = 10
  [[menus.main]]
    identifier = 'jotting'
    name = 'Jotting'
    pageRef = '/jotting/'
    weight = 11
  [[menus.main]]
    identifier = 'tags'
    name = 'Tags'
    pageRef = '/tags'
    weight = 20
  [[menus.main]]
    identifier = 'categories'
    name = 'Categories'
    pageRef = '/categories'
    weight = 30


[params]
  title = 'Rainsay Blog'
  description = 'Write my learn'
  [params.author]
    name = 'Joey'
    email = 'joey@rainsay.top'
  [params.header] 
    [params.header.title]
      name = 'Rainsay Note Blog'
  [params.home]
    [params.home.profile]
      avatarUrl = '/img/avatar.jpg'
      title = '学无止境'
      subtitle = 'ge pi, shui jiao'
  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
  [params.page]
    [params.page.code]
      copy = true
